version: "3.9"

services:
  neo4j:
    image: neo4j:5.18.0-community
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/changeit
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  mage:
    image: mageai/mageai:latest
    restart: unless-stopped
    environment:
      USER_CODE_PATH: /home/src
      PROJECT_NAME: translinguistic_nlp
    ports:
      - "6789:6789"
    volumes:
      - ./mage:/home/src
      - ./data:/home/src/data

  pipeline:
    build: .
    profiles: ["pipeline"]
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changeit
    volumes:
      - .:/app
    command: ["python", "scripts/run_pipeline.py", "--config", "config/pipeline.yaml"]

  trainer:
    build: .
    profiles: ["trainer"]
    depends_on:
      - pipeline
    volumes:
      - .:/app
    command: ["python", "scripts/train_gnn.py", "--config", "config/pipeline.yaml"]

  dashboard:
    build: .
    profiles: ["dashboard"]
    depends_on:
      - pipeline
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command:
      [
        "python",
        "-m",
        "streamlit",
        "run",
        "apps/dashboard.py",
        "--server.address=0.0.0.0",
        "--server.port=8501",
      ]

  workflow:
    build: .
    profiles: ["workflow"]
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changeit
    volumes:
      - .:/app
    command: ["python", "scripts/run_workflow.py", "--config", "config/pipeline.yaml"]

  full:
    build: .
    profiles: ["full"]
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changeit
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command:
      [
        "python",
        "scripts/run_full_pipeline.py",
        "--config",
        "config/pipeline.yaml",
        "--dashboard-address",
        "0.0.0.0",
        "--dashboard-port",
        "8501",
      ]

volumes:
  neo4j-data:
  neo4j-logs:
